### PR TITLE
[Documentation] Basic blockchain operations

### PR DESCRIPTION
**Pull request by okdas**
## Summary

One of the items requested by participants of TestNet is a documentation on basic operations such as creating/importing addresses, sending tokens, etc.

## Issue

- #451

## Type of change

Select one or more:

- [ ] New feature, functionality or library
- [ ] Bug fix
- [ ] Code health or cleanup
- [x] Documentation
- [ ] Other (specify)

## Testing

- [ ] **Unit Tests**: `make go_develop_and_test`
- [ ] **LocalNet E2E Tests**: `make test_e2e`
- [ ] **DevNet E2E Tests**: Add the `devnet-test-e2e` label to the PR. **THIS IS VERY EXPENSIVE**, so only do it after all the reviews are complete.
- [x] **Documentation changes**: `make docusaurus_start`

## Sanity Checklist

- [ ] I have tested my changes using the available tooling
- [ ] I have commented my code
- [ ] I have performed a self-review of my own code; both comments & source code
- [ ] I create and referenced any new tickets, if applicable
- [ ] I have left TODOs throughout the codebase, if applicable

### CODE REVIEW

**Review by Olshansk — APPROVED** [review]
@okdas Please review the changes I made and feel free to merge if it looks good to you.

**Review by Olshansk — CHANGES_REQUESTED** [review]
Merge with main after docs refactor

**Comment by okdas** [comment]
I put it under "operate".

@Olshansk should be g2g now!

Screenshot 2024-04-12 at 1 31 09 PM

**Review by Olshansk — APPROVED** [review]
@okdas PTAL at the changes I made (reference, double check, etc). Other than that, LGTM!

**Pull request merged**
