### PR TITLE
fix: ensure stable_marshaler_all option on all proto files

### PR DESCRIPTION
**Pull request by bryanchriswhite**
## Summary

Run `make fix_proto_unstable_marshalers`.

## Issue

Resolves non-deterministic serialization due to map types in protobuf message fields.

- #761

## Type of change

Select one or more:

- [ ] New feature, functionality or library
- [x] Bug fix
- [x] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

- [ ] **Documentation**: `make docusaurus_start`; only needed if you make doc changes
- [ ] **Unit Tests**: `make go_develop_and_test`
- [ ] **LocalNet E2E Tests**: `make test_e2e`
- [ ] **DevNet E2E Tests**: Add the `devnet-test-e2e` label to the PR.

## Sanity Checklist

- [ ] I have tested my changes using the available tooling
- [ ] I have commented my code
- [ ] I have performed a self-review of my own code; both comments & source code
- [ ] I create and reference any new tickets, if applicable
- [ ] I have left TODOs throughout the codebase, if applicable

### CODE REVIEW

**Review by okdas — APPROVED** [review]
Thanks! Let's get this in so we can do a re-genesis asap! :)

**Review by Olshansk — APPROVED** [review]
@bryanchriswhite Should we add a TODO to run the tool from #770 in CI?

**Comment by okdas** [comment]
> @bryanchriswhite Should we add a TODO to run the tool from #770 in CI?

I wanted to add it alongside https://github.com/cosmos/gosec - can create a ticket for both, 👍 👎 ?

**Comment by Olshansk** [comment]
@okdas 

> I wanted to add it alongside [cosmos/gosec](https://github.com/cosmos/gosec) - can create a ticket for both, 👍 👎 ?

Sounds good to me.

**Pull request merged**
