### PR TITLE
[SMT] Updated smt release from v0.9.2 -> v0.10.2

### PR DESCRIPTION
**Pull request by Olshansk**
## Summary

Updating the SMT release post audit.

## Issue

- #462

## Type of change

Select one or more:

- [ ] New feature, functionality or library
- [ ] Bug fix
- [x] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

- [ ] **Unit Tests**: `make go_develop_and_test`
- [ ] **LocalNet E2E Tests**: `make test_e2e`
- [ ] **DevNet E2E Tests**: Add the `devnet-test-e2e` label to the PR. **THIS IS VERY EXPENSIVE**, so only do it after all the reviews are complete.
- [ ] **Documentation changes**: `make docusaurus_start`

## Sanity Checklist

- [ ] I have tested my changes using the available tooling
- [ ] I have commented my code
- [ ] I have performed a self-review of my own code; both comments & source code
- [ ] I create and referenced any new tickets, if applicable
- [ ] I have left TODOs throughout the codebase, if applicable

### CODE REVIEW

**Review by red-0ne — CHANGES_REQUESTED** [review]
Could you please remove
```
// replace github.com/cosmos/cosmos-sdk => github.com/rollkit/cosmos-sdk v0.50.1-rollkit-v0.11.19-no-fraud-proofs
replace github.com/pokt-network/smt => github.com/pokt-network/smt v0.9.3-0.20240321060129-e3dbbbd9f97d
```

Present at the end of the file. It was used to get the latest smt changes back then.

**Review by bryanchriswhite — APPROVED** [review]
:+1:

**Review by Olshansk — COMMENTED** [review]
Self review done.

**Review by red-0ne — APPROVED** [review]
LGTM :+1:

**Pull request merged**
