### PR TITLE
[Docs] Relay session & claim/proof diagrams

### PR DESCRIPTION
**Pull request by bryanchriswhite**
## Summary

Incorporates [RPC Session Life-Cycle](https://www.notion.so/buildwithgrove/RPC-Session-Life-cycle-4bcf9f97e46540a0962cbc41f29a485d) into docusaurus docs.

## Issue

- [MVT features table](https://www.notion.so/buildwithgrove/Minimum-Viable-Testnet-Success-Criteria-baa2392d0c934f408a277c6afa1b226c?pvs=4#e9bed3470316427998c8ab604bbfdff6)
- #159 

## Type of change

Select one or more:

- [ ] New feature, functionality or library
- [ ] Bug fix
- [ ] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

- [ ] **Unit Tests**: `make go_develop_and_test`
- [ ] **LocalNet E2E Tests**: `make test_e2e`
- [ ] **DevNet E2E Tests**: Add the `devnet-test-e2e` label to the PR. **THIS IS VERY EXPENSIVE**, so only do it after all the reviews are complete.
- [x] **Documentation changes**: `make docusaurus_start`

## Sanity Checklist

- [ ] I have tested my changes using the available tooling
- [ ] I have commented my code
- [ ] I have performed a self-review of my own code; both comments & source code
- [ ] I create and referenced any new tickets, if applicable
- [ ] I have left TODOs throughout the codebase, if applicable

### CODE REVIEW

**Comment by Olshansk** [comment]
@bryanchriswhite Aiming to review this by mid week.

**Comment by Olshansk** [comment]
@bryanchriswhite Just a heads up that I started reviewing this!

**Review by Olshansk — APPROVED** [review]
@bryanchriswhite I haven't had a chance to review this in detail and don'tw ant to keep the PR sitting any longer. 

Can you merg it in as is w/ a `TODO_TECHDEBT(@Olshansk): review in detail due to auto-approval in #478`?

**Comment by bryanchriswhite** [comment]
```mermaid
%% ---
%% displayMode: compact
%% ---
gantt    
    title Session Relay / Claim / Proof Windows
    dateFormat ss
    axisFormat %S
    tickInterval 1second

    section Relays
        Session N Start : milestone, sns, 00, 0s
        num_blocks_per_session          :nbps, 00, 4s
        Session N End :milestone, sne, after nbps, 0s
        grace_period_end_offset_blocks : gpof, after sne, 2s
        Session N+1 Start : milestone, after sne, 0s
    section Claim Window
        claim_window_open_offset_blocks : cwob, after sne, 10ms
        Session N Claim Window Open : milestone, cwo, after cwob, 0s
        claim_window_close_offset_blocks : cwcb, after cwo, 4s
        Session N Claim Window Close : milestone, cwc, after cwcb, 0s
    section Proof Window
        proof_window_open_offset_blocks : pwob, after cwc, 10ms
        Session N Proof Window Open : milestone, pwo, after pwob, 0s
        proof_window_close_offset_blocks : pwcb, after pwo, 4s
        Session N PRoof Window Close : milestone, pwc, after pwcb, 0s

```

```mermaid
timeline
    title Session Claim/Proof Windows
    
    section Session
    Session
    : session N starts
    : relays for session N
    : num_blocks_per_session blocks elapse 
    : session N ends    
    section Claim Window
    Claim window & grace period
    : late relays for session N
    : session_grace_period blocks elapse
    : grace period ends
    
    : claim_window_open _offset_blocks - session_grace_period blocks elapse
    : claim window opens
    : claims for session N
    : claim_window_close _offset_blocks - session_grace_period blocks elapse
    : claim window closes
    section Proof Window
    Proof window
    : proof_window_open _offset_blocks  blocks elapse
    : proof window opens
    : proofs for session N
    : proof_window_close _offset_blocks blocks elapse
    : proof window closes

```

**Pull request merged**
