### PR TITLE
[Code Health] refactor: rename `ApplicationTransfer` msgs

### PR DESCRIPTION
**Pull request by bryanchriswhite**
## Summary

- Renaming the application module `TransferApplicationStake` messages to `TransferApplication`

## Depends on 

- #743

## Dependents

- #789

## Issue

- #657

## Type of change

Select one or more:

- [ ] New feature, functionality or library
- [ ] Bug fix
- [x] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

- [ ] **Documentation**: `make docusaurus_start`; only needed if you make doc changes
- [ ] **Unit Tests**: `make go_develop_and_test`
- [ ] **LocalNet E2E Tests**: `make test_e2e`
- [ ] **DevNet E2E Tests**: Add the `devnet-test-e2e` label to the PR.

## Sanity Checklist

- [x] I have tested my changes using the available tooling
- [ ] I have commented my code
- [x] I have performed a self-review of my own code; both comments & source code
- [ ] I create and reference any new tickets, if applicable
- [ ] I have left TODOs throughout the codebase, if applicable

### CODE REVIEW

**Review by Olshansk — CHANGES_REQUESTED** [review]
@bryanchriswhite I like the change from `TransferAppStake` to `TransferApp` but I don't think we should conflate `ParamApplicationTransferAndUnbondingPeriodSessions`.

We need an unbonding period to avoid weak subjectivity, but transferring applications should be g2g at the beginning of the next session. 

Lmk if this doesn't align with what we discussed offline yesterday.

**Comment by bryanchriswhite** [comment]
> We need an unbonding period to avoid weak subjectivity, but transferring applications should be g2g at the beginning of the next session.

You are correct. :+1: Thanks for calling this out and for adding more perspective! :pray:

**Review by Olshansk — CHANGES_REQUESTED** [review]
@bryanchriswhite Per your [last comment](https://github.com/pokt-network/poktroll/pull/788#issuecomment-2330832035), can you update the PR title and description please. I'm not sure what to review atm.

**Comment by red-0ne** [comment]
> We need an unbonding period to avoid weak subjectivity, but transferring applications should be g2g at the beginning of the next session.

@bryanchriswhite, @Olshansk. The reason why the unbonding period (or similar) needs to be applied here is that if the source application has requested work, then it should pay for it when settling pending claims.

Otherwise the application would no longer exist to have its stake burned. Unless we keep some kind of track in order to burn the destination app stake, which I believe is more complicated than enforcing an unbonding period.

The unbonding period logic has all the pre-requisites to avoid missing the last burn:
* Marks the application as inactive for the upcoming session (no work could be requested after) [x/session/keeper/session_hydrator.go#L149](https://github.com/pokt-network/poktroll/blob/main/x/session/keeper/session_hydrator.go#L149)
* Keeps the application hanging until the next `SettlePendingClaims`.

**Comment by bryanchriswhite** [comment]
> Otherwise the application would no longer exist to have its stake burned. Unless we keep some kind of track in order to burn the destination app stake, which I believe is more complicated than enforcing an unbonding period.

I've updated the transfer period to include the blocks between session end and proof window close in #789. I.e., the destination is created and the source removed after settlement of the last "active" session. It's quite similar to how the unbonding period works; `Application#IsActive()` is sensitive to the transfer session end now as well.

**Review by Olshansk — APPROVED** [review]

**Review by red-0ne — APPROVED** [review]
Clean and focused changes :sparkles:

**Pull request merged**
