### PR TITLE
feat: fix imports

### PR DESCRIPTION
**Pull request by h5law**
### Human Summary

Add bash script to add goimports-reviser import grouping excluding files where scaffolding comments are in the import area. This may need to be improved upon in fututre but its a start at least.

I also include all the changes it makes

_NOTE: Go Imports Reviser removes those ignite scaffold comments from the imports block and I dont have the bash foo to solve this rn and GPT didnt either. So I manually fixed._

### Summary generated by Reviewpad on 17 Dec 23 02:19 UTC
This pull request includes the following changes:

1. The file `key_gateway.go` in the `x/gateway/types` package has undergone changes in the import section.
2. The file `client_integration_test.go` has changes related to package imports.
3. The file `errors.go` in the `pkg/appgateserver/config` package has undergone import and variable changes.
4. The file `x/tokenomics/keeper/query_params_test.go` includes import additions and removals.
5. The file `goimports-revisor.sh` is a new script that processes Go files with specific flags and exclusions.
6. The file `params_test.go` has changes in the import statements.
7. The file `tx.go` in the `x/gateway/client/cli` directory includes import additions and removals.
8. The file `session_steps_test.go` includes changes to import statements and code.
9. The file `urls.go` in the `pkg/sdk` package has import statement modifications.
10. The file `replay_client_example_test.go` has changes in import statements.
11. The file `genesis.go` in the `x/session/types` package has import and comment changes.
12. The file `unstake_application.go` has an unused import removal.
13. The file `tokenomics/types/genesis.go` has import block removal and constant addition.
14. The file `helpers_test.go` has import additions, removals, and repositioning.
15. The file `tx.go` in the `x/tokenomics/client/cli` package includes import statement modifications.
16. The file `delegate_to_gateway.go` has import reordering and movement.
17. The file `genesis_test.go` in the `x/tokenomics/types` package includes import order changes.
18. The file `session_steps_test.go` has code and import changes.
19. The file `urls.go` has a blank line addition.
20. The file `testutil/testerrors/require.go` has import statement changes and error handling modifications.
21. The file `genesis_test.go` in the `x/tokenomics/types` package has import order changes and an added import.
22. The file `relay.go` has an import change.
23. The file `errors.go` in the `pkg/appgateserver` package has import changes and variable definition.
24. The file `key_supplier.go` in the `types` package has import updates.
25. The file `message_delegate_to_gateway_test.go` in the `types` package has import statement changes.

Please review the complete diff for more details on each file.

## Issue

Related https://github.com/pokt-network/poktroll/issues/270

## Type of change

Select one or more:

- [ ] New feature, functionality or library
- [ ] Bug fix
- [x] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

- [ ] **Run all unit tests**: `make go_develop_and_test`
- [ ] **Run E2E tests locally**: `make test_e2e`
- [ ] **Run E2E tests on DevNet**: Add the `devnet-test-e2e` label to the PR. This is VERY expensive, only do it after all the reviews are complete.

## Sanity Checklist

- [ ] I have tested my changes using the available tooling
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, updated documentation and left TODOs throughout the codebase

### CODE REVIEW

**Comment by h5law** [comment]
@okdas seems CI fails when comments are in import blocks?

**Comment by h5law** [comment]
go lint fails bc goimports-reviser removes comments from import blocks and scaffold puts them in there so..,..

**Review by Olshansk — CHANGES_REQUESTED** [review]
I haven't done research on the different types of import linters so I don't have a strong opinion on this and interested in hearing @bryanchriswhite's opinion.

1. @h5law Why this over goimports which is already done?
2. @bryanchriswhite Wdyt?
3. If we do go with this approach though (TBD), I'm seeing some outstanding items in this PR:
	1. Update the Makefile to use this importer
	2. Updating the CI to use this importer
	3. Removing `./tools/scripts/goimports` because we should only have one import linting script.

**Comment by bryanchriswhite** [comment]
See https://github.com/pokt-network/poktroll/pull/253#issuecomment-1853524297 and https://github.com/pokt-network/poktroll/pull/253#issuecomment-1851548350.
image

**Comment by Olshansk** [comment]
Could/should we close this one out?

**Comment by h5law** [comment]
@Olshansk going to close this one - its outdated and better to add tooling instead of a simple fix like this.

**Pull request closed without merging**
