### PR TITLE
[Tooling] Add application stake/unstake/delegate logs

### PR DESCRIPTION
**Pull request by red-0ne**
## Summary

Add `Application` logs
* `StakeApplication`
* `UnstakeApplication`
* `DelegateToGateway`
* `UndelegateFromGateway`
image
image

## Issue

- [MVT Features table](https://www.notion.so/buildwithgrove/Minimum-Viable-Testnet-Success-Criteria-baa2392d0c934f408a277c6afa1b226c)

## Type of change

Select one or more:

- [ ] New feature, functionality or library
- [ ] Bug fix
- [ ] Code health or cleanup
- [ ] Documentation
- [x] Other (specify): Add dashboard & link

## Sanity Checklist

- [x] I have tested my changes using the available tooling
- [ ] I have commented my code
- [x] I have performed a self-review of my own code; both comments & source code
- [ ] I create and reference any new tickets, if applicable
- [ ] I have left TODOs throughout the codebase, if applicable

### CODE REVIEW

**Review by Olshansk — CHANGES_REQUESTED** [review]
@red-0ne Any chance you can add a screenshot of what this added? It's hard to review the json.

**Review by Olshansk — APPROVED** [review]
Pre-emtively approving to not block the merge, but please update the PR description and add screenshots in the future.

**Comment by red-0ne** [comment]
@Olshansk , Screenshots added.

**Review by Olshansk — APPROVED** [review]
Ty!

**Pull request merged**
