### PR TITLE
[Documentation] Refactor poktroll documentation so its easier to navigate

### PR DESCRIPTION
**Pull request by Olshansk**
## Summary

- No changes to the actual documentation
- Create navigation bar tabs
- Format the sidebar styling
- Auto-expand all sidebars
- Add search functionality (added after video was recorded)

**Before:**

https://github.com/pokt-network/poktroll/assets/1892194/b6bcc4fa-6504-432f-90ea-ab36f7bd4fdc

**After:**

https://github.com/pokt-network/poktroll/assets/1892194/5635ca1d-9f8d-48c5-906b-574c95c11b26

## Issue

- #460

## Type of change

Select one or more:

- [ ] New feature, functionality or library
- [ ] Bug fix
- [ ] Code health or cleanup
- [x] Documentation
- [ ] Other (specify)

## Testing

- [x] **Documentation changes**: `make docusaurus_start`

## Sanity Checklist

- [x] I have tested my changes using the available tooling

### CODE REVIEW

**Comment by Olshansk** [comment]
@okdas I couldn't find any github workflows that update https://dev.poktroll.com/. Where is it?

Reason why I ask:

Screenshot 2024-04-10 at 4 40 20 PM

**Comment by okdas** [comment]
> @okdas I couldn't find any github workflows that update https://dev.poktroll.com/. Where is it?

This is the one: https://github.com/pokt-network/poktroll/blob/main/.github/workflows/upload-pages-artifact.yml

**Review by okdas — APPROVED** [review]
I like the new UI, all links seem to work. I say let's merge and see if the search index works on dev.poktroll.com.

**Comment by okdas** [comment]
@Olshansk there's a conflict now after the other branch is merged - I can take care of it - just LMK.

**Pull request merged**
