### PR TITLE
[SDK] Track pb.go files 

### PR DESCRIPTION
**Pull request by red-0ne**
## Summary

This PR adds tracking to `.pb.go` generated files and removes the corresponding entry from `.gitignore`

## Issue

In order to use the generated types corresponding to `proktroll` protobuf definitions from external repositories, the generated `.pb.go` files need to be added to the repo.

This is currently the only viable solution to decouple the `SDK` and extract it to its own repo.

- #510 

## Type of change

Select one or more:

- [x] New feature, functionality or library
- [ ] Bug fix
- [ ] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

**Documentation changes** (only if making doc changes)
- [ ] `make docusaurus_start`; only needed if you make doc changes

**Local Testing** (only if making code changes)
- [ ] **Unit Tests**: `make go_develop_and_test`
- [ ] **LocalNet E2E Tests**: `make test_e2e`
- See [quickstart guide](https://dev.poktroll.com/developer_guide/quickstart) for instructions

**PR Testing** (only if making code changes)
- [ ] **DevNet E2E Tests**: Add the `devnet-test-e2e` label to the PR.
    - **THIS IS VERY EXPENSIVE**, so only do it after all the reviews are complete.
    - Optionally run `make trigger_ci` if you want to re-trigger tests without any code changes
    - If tests fail, try re-running failed tests only using the GitHub UI as shown [here](https://github.com/pokt-network/poktroll/assets/1892194/607984e9-0615-4569-9452-4c730190c1d2)

## Sanity Checklist

- [x] I have tested my changes using the available tooling
- [ ] I have commented my code
- [x] I have performed a self-review of my own code; both comments & source code
- [ ] I create and reference any new tickets, if applicable
- [ ] I have left TODOs throughout the codebase, if applicable

### CODE REVIEW

**Review by Olshansk — CHANGES_REQUESTED** [review]
Since we're committing `.pb.go` files, I thhink we should remove (or comment out with a comment explaining why) any `proto_regen` commands in the builds.

This is going to ensure we avoid discrepancies between the source and binary files.

Open to push back but am pretty sure this is the way to go.

@okdas wdyt

Screenshot 2024-05-21 at 9 53 56 AM

**Comment by okdas** [comment]
@Olshansk I agree. If we remove `proto_regen` from CI, we will achieve reproducible builds. Let's remove this step.

We can introduce another CI step that will fail if there's a difference between the committed pb files and the protobufs generated by CI. This way, we can catch situations where `.proto` files were changed but `.pb.go` files were not updated (or were updated incorrectly).

Does that make sense? If so, I'll create a ticket to work on that.

**Comment by Olshansk** [comment]
`We can introduce another CI step that will fail if there's a difference between the committed pb files and the protobufs generated by CI`

@red-0ne let's add a TODO_TECHDEBT for ☝️  but seems overkill for now

**Review by Olshansk — APPROVED** [review]
1. Made small edits
2. I added devnet-e2e test tags
3. Pushed

Feel free to merge once tests are 🟢

**Comment by red-0ne** [comment]
Reviewdog checks are failing due to big diff but unit and e2e tests are passing.

image

Merging

**Pull request merged**
